require: rubocop-sorbet
inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'test.rb'
Naming/MethodParameterName:
  MinNameLength: 1
Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Max: 16